/**
 * Mapping between domain entities and SQLite rows. `kind` drives the conversion:
 * booleans are stored as 0/1 and arrays/objects as JSON text.
 */

export type ColumnKind = 'text' | 'int' | 'bool' | 'json'

export interface TableSpec {
  table: string
  key: string
  columns: Record<string, ColumnKind>
  /** Index name used by `Collection.where` -> column it filters on. */
  indexes: Record<string, string>
}

const timestamps = { created_at: 'text', updated_at: 'text' } as const

export const TABLES = {
  organizations: {
    table: 'organizations',
    key: 'id',
    columns: {
      id: 'text',
      name: 'text',
      timezone: 'text',
      support_email: 'text',
      support_contact_name: 'text',
      record_version: 'int',
      ...timestamps,
    },
    indexes: {},
  },
  users: {
    table: 'users',
    key: 'id',
    columns: {
      id: 'text',
      display_name: 'text',
      email: 'text',
      auth_subject: 'text',
      password_hash: 'text',
      password_updated_at: 'text',
      status: 'text',
      last_login_at: 'text',
      created_at: 'text',
    },
    indexes: { by_email: 'email' },
  },
  sessions: {
    table: 'sessions',
    key: 'id',
    columns: {
      id: 'text',
      user_id: 'text',
      token_hash: 'text',
      active_vendor_id: 'text',
      created_at: 'text',
      last_seen_at: 'text',
      expires_at: 'text',
      revoked_at: 'text',
    },
    indexes: { by_token_hash: 'token_hash', by_user: 'user_id' },
  },
  memberships: {
    table: 'memberships',
    key: 'id',
    columns: { id: 'text', organization_id: 'text', user_id: 'text', role: 'text' },
    indexes: { by_user: 'user_id', by_organization: 'organization_id' },
  },
  vendors: {
    table: 'vendors',
    key: 'id',
    columns: {
      id: 'text',
      organization_id: 'text',
      company_name: 'text',
      category: 'text',
      contact_name: 'text',
      contact_email: 'text',
      lifecycle: 'text',
      invited_at: 'text',
      property_tags: 'json',
      archived_at: 'text',
      archive_reason: 'text',
      record_version: 'int',
      ...timestamps,
    },
    indexes: { by_organization: 'organization_id', by_lifecycle: 'lifecycle' },
  },
  vendorMemberships: {
    table: 'vendor_memberships',
    key: 'id',
    columns: {
      id: 'text',
      organization_id: 'text',
      vendor_id: 'text',
      user_id: 'text',
      verified_at: 'text',
    },
    indexes: { by_vendor: 'vendor_id', by_user: 'user_id' },
  },
  templates: {
    table: 'templates',
    key: 'id',
    columns: {
      id: 'text',
      organization_id: 'text',
      name: 'text',
      description: 'text',
      version: 'int',
      archived_at: 'text',
      record_version: 'int',
      ...timestamps,
    },
    indexes: { by_organization: 'organization_id' },
  },
  templateItems: {
    table: 'template_items',
    key: 'id',
    columns: {
      id: 'text',
      template_id: 'text',
      title: 'text',
      instructions: 'text',
      required: 'bool',
      expiration_required: 'bool',
      collect_issue_date: 'bool',
      sort_order: 'int',
    },
    indexes: { by_template: 'template_id' },
  },
  requirements: {
    table: 'requirements',
    key: 'id',
    columns: {
      id: 'text',
      organization_id: 'text',
      vendor_id: 'text',
      source_template_id: 'text',
      source_template_version: 'int',
      source_item_id: 'text',
      title: 'text',
      instructions: 'text',
      required: 'bool',
      expiration_required: 'bool',
      collect_issue_date: 'bool',
      sort_order: 'int',
      due_date: 'text',
      retired_at: 'text',
      retired_reason: 'text',
      effective_submission_id: 'text',
      record_version: 'int',
      ...timestamps,
    },
    indexes: { by_vendor: 'vendor_id', by_organization: 'organization_id' },
  },
  submissions: {
    table: 'submissions',
    key: 'id',
    columns: {
      id: 'text',
      organization_id: 'text',
      vendor_id: 'text',
      requirement_id: 'text',
      version_number: 'int',
      state: 'text',
      file_object_id: 'text',
      issue_date: 'text',
      expiration_date: 'text',
      submitted_by: 'text',
      submitted_by_label: 'text',
      submitted_on_behalf: 'bool',
      submitted_at: 'text',
      decided_at: 'text',
      withdrawn_at: 'text',
      superseded_by_submission_id: 'text',
      record_version: 'int',
    },
    indexes: {
      by_requirement: 'requirement_id',
      by_vendor: 'vendor_id',
      by_state: 'state',
      by_organization: 'organization_id',
    },
  },
  files: {
    table: 'files',
    key: 'id',
    columns: {
      id: 'text',
      organization_id: 'text',
      storage_key: 'text',
      original_filename: 'text',
      detected_mime: 'text',
      byte_size: 'int',
      scan_status: 'text',
      created_by: 'text',
      created_at: 'text',
    },
    indexes: { by_organization: 'organization_id', by_storage_key: 'storage_key' },
  },
  reviewEvents: {
    table: 'review_events',
    key: 'id',
    columns: {
      id: 'text',
      organization_id: 'text',
      submission_id: 'text',
      actor_id: 'text',
      actor_label: 'text',
      decision: 'text',
      reason: 'text',
      created_at: 'text',
    },
    indexes: { by_submission: 'submission_id', by_organization: 'organization_id' },
  },
  invitations: {
    table: 'invitations',
    key: 'id',
    columns: {
      id: 'text',
      organization_id: 'text',
      vendor_id: 'text',
      invited_email: 'text',
      token_hash: 'text',
      expires_at: 'text',
      redeemed_at: 'text',
      redeemed_by_user_id: 'text',
      revoked_at: 'text',
      created_by: 'text',
      created_at: 'text',
    },
    indexes: { by_vendor: 'vendor_id', by_token_hash: 'token_hash' },
  },
  notifications: {
    table: 'notifications',
    key: 'id',
    columns: {
      id: 'text',
      organization_id: 'text',
      vendor_id: 'text',
      type: 'text',
      recipient: 'text',
      recipient_label: 'text',
      subject: 'text',
      body: 'text',
      items: 'json',
      status: 'text',
      idempotency_key: 'text',
      attempt_count: 'int',
      next_attempt_at: 'text',
      sent_at: 'text',
      last_error: 'text',
      manual: 'bool',
      created_at: 'text',
    },
    indexes: {
      by_vendor: 'vendor_id',
      by_idempotency_key: 'idempotency_key',
      by_status: 'status',
      by_organization: 'organization_id',
    },
  },
  activity: {
    table: 'activity_events',
    key: 'id',
    columns: {
      id: 'text',
      organization_id: 'text',
      vendor_id: 'text',
      actor_id: 'text',
      actor_label: 'text',
      actor_role: 'text',
      event_type: 'text',
      target_id: 'text',
      summary: 'text',
      reason: 'text',
      metadata: 'json',
      vendor_visible: 'bool',
      created_at: 'text',
    },
    indexes: { by_vendor: 'vendor_id', by_event_type: 'event_type', by_organization: 'organization_id' },
  },
  importBatches: {
    table: 'import_batches',
    key: 'id',
    columns: {
      id: 'text',
      organization_id: 'text',
      request_key: 'text',
      row_count: 'int',
      status: 'text',
      template_id: 'text',
      created_at: 'text',
      created_vendor_ids: 'json',
    },
    indexes: { by_request_key: 'request_key', by_organization: 'organization_id' },
  },
  requests: {
    table: 'request_records',
    key: 'key',
    columns: { key: 'text', result_json: 'text', created_at: 'text' },
    indexes: {},
  },
} as const satisfies Record<string, TableSpec>

export type TableName = keyof typeof TABLES
